const data = [
    {
        product_name: 'espresso',
        id :1,
        price: 10000,
        priceStyle: 'Rp. 10.000',
        qty: 1,
        picture: "./photo/jeremy-ricketts-6ZnhM-xBpos-unsplash.png",
    },
    {
        product_name: 'coffee latte',
        id :2,
        price: 15000,
        priceStyle: 'Rp. 15.000',
        qty: 1,
        picture: "./photo/bear.png",
    },
    {
        product_name: 'cappucino',
        id :3,
        price: 5000,
        priceStyle: 'Rp. 5.000',
        qty: 1,
        picture: "./photo/firdaus-roslan-pN769u0KHNA-unsplash.png",
    },
    {
        product_name: 'red velvet',
        id :4,
        price: 33000,
        priceStyle: 'Rp. 33.000',
        qty: 1,
        picture: "./photo/redvelvet.png",
    },
    {
        product_name: 'chocorum',
        id :5,
        price: 28000,
        priceStyle: 'Rp. 28.000',
        qty: 1,
        picture: "./photo/chocorum.png",
    },
    {
        product_name: 'black forest',
        id :6,
        price: 30000,
        priceStyle: 'Rp. 30.000',
        qty: 1,
        picture: "./photo/blackforest.png",
    },
    {
        product_name: 'chicken katsu',
        id :7,
        price: 60000,
        priceStyle: 'Rp. 60.000',
        qty: 1,
        picture: "./photo/chickenkatsu.png",
    },
    {
        product_name: 'salmon truffle',
        id :8,
        price: 60000,
        priceStyle: 'Rp. 60.000',
        qty: 1,
        picture: "./photo/salmon.png",
        
    },
    {
        product_name: 'Wiener Schnitzel',
        id :9,
        price: 69000,
        priceStyle: 'Rp. 69.000',
        qty: 1,
        picture: "./photo/wiener.png",
    },
]
const chart = [ ]
